Cotizador/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('formulario.urls', namespace="formulario")),
    url(r'administrador/', include('administrador.urls', namespace="administrador")),
    url(r'propuesta/', include('propuesta.urls', namespace="propuesta")),
    url(r'^admin/', include(admin.site.urls)),
]

formulario/urls.py
'''
Created on 26/11/2015

@author: jose
'''

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^crear/$', views.crearRuta, name='crearRuta'),
    url(r'^mapa/$', views.verMapa, name='verMapa'),
    url(r'^mapa/informcacion/(?P<id>[0-9]+)/(?P<caminon>[0-9]+)$', views.verMapa2, name='verMapa2'),
    url(r'^tabla/$', views.verTabla, name='verTabla'),
]

propuesta/urls.py
'''
Created on 8/01/2016

@author: jose
'''
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^infomracion/$', views.datosCotizador, name='info'),
    url(r'^pdf/$', views.pdf, name='pdf'),
    url(r'^ver/(?P<slug>[^\.]+)/$', views.ver, name='ver'),
    url(r'^(?P<slug>[^\.]+)/$', views.propuesta, name='propuesta'),
]

propuesta/models.py
from django.db import models
from formulario.models import Cotizacion

# Create your models here.

class Confirmacion(models.Model):
    fecha = models.DateField(auto_now_add=True)
    puestos = models.CharField(max_length=200)
    cedula = models.CharField(max_length=200)
    telefono = models.CharField(max_length=200)
    tipo = models.CharField(max_length=200)
    cotizacion= models.ForeignKey(Cotizacion,on_delete=models.CASCADE)
    

propuesta/views.py
from django.shortcuts import render,get_object_or_404
from administrador.models import formulario
from formulario.models import Cotizacion
from django.http import HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
import json
from Cotizador import settings
from django.core import serializers
from propuesta.models import Confirmacion
# Create your views here.

def propuesta(request,slug):
    propuesta = get_object_or_404(formulario,slug = slug)
    '''cotizacion = get_object_or_404(Cotizacion,pk = propuesta.cotizacion_id)
    context = {'propuesta':propuesta,'cotizacion':cotizacion}'''
    context = {'propuesta':propuesta}
    return render(request,'propuesta/index.html',context)

def ver(request,slug):
    propuesta = get_object_or_404(formulario,slug = slug)
    propuesta.vista = True
    propuesta.save()
    cotizacion = get_object_or_404(Cotizacion,pk = propuesta.cotizacion_id)
    serial = serializers.serialize('json', [ cotizacion, ])
    context = {'propuesta':propuesta,'cotizacion':cotizacion,'serial':serial}    
    return render(request,'propuesta/propuesta.html',context)

def datosCotizador(request):
    cotizacion = get_object_or_404(Cotizacion,pk = request.POST['idcot'])
    confirmacion = Confirmacion()
    confirmacion.puestos = request.POST['puestos']
    confirmacion.cedula = request.POST['identificacion']
    confirmacion.telefono = request.POST['telefono']
    confirmacion.tipo = request.POST['tipo']
    confirmacion.cotizacion = cotizacion
    confirmacion.save()
    
    con = get_object_or_404(Confirmacion,pk = confirmacion.pk)
    return HttpResponse('ok')
    
def pdf(request):
    with open(settings.BASE_DIR+'/propuesta/static/contrato.pdf', 'rb') as pdf:
        response = HttpResponse(pdf.read(),content_type='application/pdf')
        response['Content-Disposition'] = 'filename=contrato.pdf'
        return response
    pdf.closed

propuesta/templates/propuesta/index.html
{% load staticfiles %}
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Propuesta sival</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <link href="{% static 'formulario/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'propuesta/css/principal.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="col-sm-6 left"></div>
        <div class="col-sm-6 right">       
            <div class="header">                               
                <span class="line-red"></span>
                <h4>transportes sival</h4>
                <span class="line-red"></span>
            </div>  
            <div class="main">    
                <div class="box sidebar">
                    <div class="line-vertical">
                        <span class="line-vertical"></span>
                        <p>s</p>
                        <p>i</p>
                        <p>v</p>
                        <p>a</p>
                        <p>l</p>
                    </div>
                </div>    
                <div class="box content">
                    <h3>En el</h3>
                    <h2>corazón</h2>
                    <h3>de la</h3>
                    <h2>carretera</h2>
                    <div class="frace">
                        <p>Donde quieras que vayas,</p>
                        <p>ve con todo tu corazón.</p>
                        <span class="cent">Confucio</span>
                    </div>
                </div>    
                <div class="box sidebar">
                    <div class="line-vertical">
                        <span class="line-vertical"></span>
                        <p>2</p>
                        <p>0</p>
                        <p>1</p>
                        <p>6</p>                        
                    </div>
                </div>  
            </div>  
            <div class="footer">
                <a href="{% url 'propuesta:ver' propuesta.slug %}" class="btn">ver propuesta</a>
            </div>
        </div>
        <script type="text/javascript" src="{% static 'formulario/js/jquery-2.1.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'formulario/js/bootstrap.min.js' %}"></script>
    </body>
</html>

propuesta/templates/propuesta/propuesta.html
{% load staticfiles %}
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Sival propuesta</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'formulario/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'propuesta/css/principal.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link href="{% static 'sweetalert/dist/sweetalert.css' %}" rel="stylesheet">

        <!-- Smartsupp Live Chat script -->
        <!--Start of Zopim Live Chat Script-->
        <script type="text/javascript">
        window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
        d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
        _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
        $.src="//v2.zopim.com/?3cKlwfxkI6Ou73DUMNT5ET0b5UVvMxHM";z.t=+new Date;$.
        type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
        </script>
        <!--End of Zopim Live Chat Script-->
    </head>
    <body>
        <div class="arriba">
            <div class="micontenedor">
                <div class="texto">
                    <h1>Propuesta comercial</h1>
                    <p>Preparada para <span> {{cotizacion.nombre}} </span> por <span>Trasporte Sival</span></p>
                    <p id="fechaCotizacion"></p>
                </div>
            </div>

        </div>
        <div class="centro">
            <div class="contenedor">
                <h1>Transporte Sival</h1>
                <h2>Definición:</h2>
                <p>El transporte es una actividad del sector terciario, entendida como el desplazamiento de objetos o personas de un lugar (punto de origen) a otro (punto de destino) en un vehículo (medio o sistema de transporte) que utiliza una determinada infraestructura (red de transporte). Esta ha sido una de las actividades terciarias que mayor expansión ha experimentado a lo largo de los últimos dos siglos, debido a la industrialización; al aumento del comercio y de los desplazamientos humanos tanto a escala nacional como internacional; y los avances técnicos que se han producido y que han repercutido en una mayor rapidez, capacidad, seguridad y menor coste de los transportes.</p>
                <span></span>
            </div>
            <div class="contenedor">
                <h1>Propuesta económica</h1>
                <p>Selecciona el tipo de bus en el cual desea viajar.</p>
                <div class="container-pro">
                    <div class="col-sm-6">
                        <button class="btn-normal" id="btn1">Bus Estándar</button>
                    </div>
                    <div class="col-sm-6">
                        <button class="btn-normal" id="btn2">Bus Premium</button>
                    </div>
                </div>    
                <div class="informacion">
                    <p>Caracteristicas del bus</p>
                    <table class="tabla" >                    
                        <tbody>
                            <tr>
                                <th>Capacidad</th>
                                <td id="t1">20-10-2015</td>                                                               
                            </tr>
                            <tr>
                                <th >Modelo</th>
                                <td id="t2">2:30pm</td>                                                               
                            </tr>
                            <tr>
                                <th>Televisor</th>
                                <td id="t3">2:30pm</td>                                                               
                            </tr>
                            <tr>
                                <th>Wifi a bordo</th>
                                <td id="t4">2:30pm</td>                                                               
                            </tr>
                            <tr>
                                <th>bluetooth conectado a parlantes</th>
                                <td id="t5">2:30pm</td>                                                               
                            </tr>
                        </tbody>
                    </table>
                    <p>Trayecto ida</p>
                    <table class="tabla" id="tab-origen">
                        <tbody>
                            
                        </tbody>
                    </table>
                    <div style="margin-top: 15px;text-align: right;">
                        <a href="{% url 'formulario:verMapa2' cotizacion.pk 1%}" target="_blank">Ver recorrido en mapa</a>
                    </div>
                    
                    {% if cotizacion.camino == 2%}
                    <p>Trayecto regreso</p>
                    <table class="tabla" id="tab-regreso">
                        <tbody>

                        </tbody>
                    </table>
                    <div style="margin-top: 15px;text-align: right;">
                        <a href="{% url 'formulario:verMapa2' cotizacion.pk 2%}" target="_blank">Ver recorrido en mapa</a>
                    </div>
                    {% endif %}
                </div>                                
                <span></span>
            </div>       
            <div class="contenedor">
                <h1>
                    Somos tu mejor opción
                </h1>
                <p>
                    Nos apaciona el sector de trasnporte y la calida del servicio. Por esto, queremos darte lo mejor y hacerte sentir muy bien. Al aceptar nuestra propuesta nos pondremos en contacto contigo para ajustar los términos y condiciones del contrato.
                </p>
                <p>
                    Consignar en la cuenta de ahorros <b>XXX</b> a nombre de <b>XXX</b>
                </p>
                <form method="post" id="formulario-repsuetsa">
                    {% csrf_token %} 
                    <div class="formulario">
                        <div style="position: relative">
                            <input type="text" placeholder="Numero de puestos">
                            <i class="fa fa-ticket fa-2x mis-iconos"></i>
                        </div>
                        <div style="position: relative">
                            <input type="text" placeholder="Cedula o NIT">
                            <i class="fa fa-credit-card fa-2x mis-iconos"></i>
                        </div>
                        <div style="position: relative">
                            <input type="text" placeholder="Telefono">
                            <i class="fa fa-phone fa-2x mis-iconos"></i>
                        </div>                    
                        <button>Aceptar propuesta</button>
                        <p>Al aceptar la propuesta está aceptando nuestros </p>
                        <p><u><a href="{% url 'propuesta:pdf' %}" target="_blank">términos y condiciones</a></u></p>
                    </div>
                </form>
                <span></span>
            </div>
        </div>
        <div class="abajo">
            <div style="display: table-cell;vertical-align: middle;">
                <h1>Contacto</h1>
                <p>
                    Si tienes alguna duda no dudes en escribirnos a coordinacion@sival.com.co
                </p>
                <p>
                    o, si lo prefieres, puedes chatear con nosotros
                </p>                
                <button>Empezar chat</button>
                <br>
                <a href="#" onclick="myFunction()"><i class="fa fa-print fa-5x" style="color: white"></i></a>
                <script>
                function myFunction() {
                    window.print();
                }
                </script>
            </div>

        </div>
        <script type="text/javascript"> 
            var idcot = "{{cotizacion.pk}}";
            var cot = '{{serial}}';
            var precio = {
                ida : '{{propuesta.precioIda}}',
                regreso: '{{propuesta.precioRegreso}}'
            };
        </script>
        <script type="text/javascript" src="{% static 'administrador/libs/jquery/jquery/dist/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'propuesta/js/principal.js' %}"></script>
        <script type="text/javascript" src="{% static 'sweetalert/dist/sweetalert.min.js' %}"></script>
    </body>
</html>