Cotizador/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('formulario.urls', namespace="formulario")),
    url(r'administrador/', include('administrador.urls', namespace="administrador")),
    url(r'propuesta/', include('propuesta.urls', namespace="propuesta")),
    url(r'^admin/', include(admin.site.urls)),
]

administrador/urls.py
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.administrador, name='administrador'),
    url(r'^json/$', views.jsonServidor, name='getjson'),
    url(r'^rutaida/(?P<id>[0-9]+)/$', views.rutaIda, name='getruta1'),
    url(r'^rutavuelta/(?P<id>[0-9]+)/$', views.rutaVuelta, name='getruta2'),
    url(r'^guardar/$', views.crearPropuesta, name='crear'),
    url(r'^propuesta/(?P<slug>[^\.]+)/$', views.darPropuesta, name='propuesta'),
    url(r'^solicitudes/$', views.HistorialSolicitud, name='solicitud'),
     url(r'^propuestas/$', views.HistorialPropuestas, name='propuestas'),
    url(r'^json2/$', views.jsonSolicitudes, name='getjson2'),
    url(r'^json3/$', views.jsonPropuestas, name='getjson3'),
]

propuesta/urls.py
'''
Created on 8/01/2016

@author: jose
'''
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^infomracion/$', views.datosCotizador, name='info'),
    url(r'^pdf/$', views.pdf, name='pdf'),
    url(r'^ver/(?P<slug>[^\.]+)/$', views.ver, name='ver'),
    url(r'^(?P<slug>[^\.]+)/$', views.propuesta, name='propuesta'),
]

administrador/models.py
from __future__ import unicode_literals

from django.db import models
from formulario.models import Cotizacion 



# Create your models here.

class formulario(models.Model):
    precioIda = models.IntegerField(null=True)
    precioRegreso = models.IntegerField(null=True)
    comentarios = models.CharField(max_length=200,null=True)
    cotizacion= models.ForeignKey(Cotizacion,on_delete=models.CASCADE)
    slug = models.SlugField(max_length = 100, unique = True)
    vista = models.BooleanField(default = False)
        
    
    

propuesta/models.py
from django.db import models
from formulario.models import Cotizacion

# Create your models here.

class Confirmacion(models.Model):
    fecha = models.DateField(auto_now_add=True)
    puestos = models.CharField(max_length=200)
    cedula = models.CharField(max_length=200)
    telefono = models.CharField(max_length=200)
    tipo = models.CharField(max_length=200)
    cotizacion= models.ForeignKey(Cotizacion,on_delete=models.CASCADE)
    

administrador/views.py
from django.shortcuts import render, get_object_or_404
from formulario.models import Cotizacion, Punto
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponse
import json
from administrador.models import formulario
from django.utils.crypto import get_random_string
from django.core.mail import send_mail
from propuesta.models import Confirmacion


BASE_DIR = '127.0.0.1:8000'
BASE_DIR_PROPUESTA = BASE_DIR+"/propuesta/"

# Create your views here.

def administrador(request):
    return render(request,'administrador/principal.html')

def jsonServidor(request):
    cotizaciones = Cotizacion.objects.filter(respondido = False).order_by('-fecha').values()
    lista = []
    for cot in cotizaciones:
        punto1 = Punto.objects.filter(cotizacion_id = cot.get('id')).filter(camino='OR').filter(secuencia=0)[0]
        punto2 = Punto.objects.filter(cotizacion_id = cot.get('id')).filter(camino='DS').filter(secuencia=0)[0]
        cot['origen'] = punto1.nombre
        cot['destino'] = punto2.nombre
        lista.append(cot)        
    dic = {"aaData":lista}
    serial2 = json.dumps(dic, cls=DjangoJSONEncoder)
    return HttpResponse(serial2)

def rutaIda(request, id):
    cotizacion = Cotizacion.objects.get(pk=id);
    puntosIda = Punto.objects.filter(cotizacion = cotizacion).filter(camino='OR').order_by('secuencia').values();
    serial = json.dumps(list(puntosIda), cls=DjangoJSONEncoder)
    return HttpResponse(serial)

def rutaVuelta(request, id):
    cotizacion = Cotizacion.objects.get(pk=id);
    puntosIda = Punto.objects.filter(cotizacion = cotizacion).filter(camino='DS').order_by('secuencia').values();
    serial = json.dumps(list(puntosIda), cls=DjangoJSONEncoder)
    return HttpResponse(serial)

def crearPropuesta(request):
    qdic = request.POST
    dic = dict(qdic.iterlists())
    cotizacion = Cotizacion.objects.get(pk=dic.get('id')[0])
    cotizacion.respondido = True
    cotizacion.save()
    form = formulario()
    form.precioIda = dic.get('cm1')[0]
    if dic.get('cm2')[0]!='':
        form.precioRegreso = dic.get('cm2')[0]
    form.comentarios = dic.get('cm3')[0]
    form.cotizacion = cotizacion
    form.slug = get_random_string(length=5)
    form.save()
    form.slug = form.slug+str(form.pk)
    form.save()
    send_mail('Propuesta sival', 'Hola '+cotizacion.nombre+'. Ingrese a la pagina '+ BASE_DIR_PROPUESTA+form.slug+ ' para ver tu propuesta', 'from@example.com',
    [cotizacion.correo], fail_silently=False)
    return HttpResponse('ok')

def darPropuesta(request,slug):
    propuesta = get_object_or_404(formulario,slug = slug)
    context = {'cm1':propuesta.precioIda,'cm2':propuesta.precioRegreso,'cm3':propuesta.comentarios}
    return render(request,'administrador/propuesta.html',context)

def HistorialSolicitud(request):
    return render(request,'administrador/solicitudes.html')

def HistorialPropuestas(request):
    return render(request,'administrador/propuesta.html')

def jsonSolicitudes(request):
    cotizaciones = Cotizacion.objects.all().values()
    lista = []
    for cot in cotizaciones:
        punto1 = Punto.objects.filter(cotizacion_id = cot.get('id')).filter(camino='OR').filter(secuencia=0)[0]
        punto2 = Punto.objects.filter(cotizacion_id = cot.get('id')).filter(camino='DS').filter(secuencia=0)[0]
        cot['origen'] = punto1.nombre
        cot['destino'] = punto2.nombre
        try:
            formu = formulario.objects.get(cotizacion_id = cot.get('id'))
            cot['pida'] = formu.precioIda
            cot['pregreso'] = formu.precioRegreso
            cot['com'] = formu.comentarios
            cot['vista'] = formu.vista
            lista.append(cot) 
        except formulario.DoesNotExist:
            cot['pida'] = 0
            cot['pregreso'] = 0
            cot['com'] = ''
            lista.append(cot) 
    dic = {"aaData":lista}
    serial2 = json.dumps(dic, cls=DjangoJSONEncoder)
    return HttpResponse(serial2)
    
def jsonPropuestas(request):
    confirmaciones = Confirmacion.objects.all().values()
#     serial = json.dumps(list(confirmaciones), cls=DjangoJSONEncoder)
    dic = {"aaData":list(confirmaciones)}
    serial2 = json.dumps(dic, cls=DjangoJSONEncoder)
    return HttpResponse(serial2)
    
    
    

propuesta/views.py
from django.shortcuts import render,get_object_or_404
from administrador.models import formulario
from formulario.models import Cotizacion
from django.http import HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
import json
from Cotizador import settings
from django.core import serializers
from propuesta.models import Confirmacion
# Create your views here.

def propuesta(request,slug):
    propuesta = get_object_or_404(formulario,slug = slug)
    '''cotizacion = get_object_or_404(Cotizacion,pk = propuesta.cotizacion_id)
    context = {'propuesta':propuesta,'cotizacion':cotizacion}'''
    context = {'propuesta':propuesta}
    return render(request,'propuesta/index.html',context)

def ver(request,slug):
    propuesta = get_object_or_404(formulario,slug = slug)
    propuesta.vista = True
    propuesta.save()
    cotizacion = get_object_or_404(Cotizacion,pk = propuesta.cotizacion_id)
    serial = serializers.serialize('json', [ cotizacion, ])
    context = {'propuesta':propuesta,'cotizacion':cotizacion,'serial':serial}    
    return render(request,'propuesta/propuesta.html',context)

def datosCotizador(request):
    cotizacion = get_object_or_404(Cotizacion,pk = request.POST['idcot'])
    confirmacion = Confirmacion()
    confirmacion.puestos = request.POST['puestos']
    confirmacion.cedula = request.POST['identificacion']
    confirmacion.telefono = request.POST['telefono']
    confirmacion.tipo = request.POST['tipo']
    confirmacion.cotizacion = cotizacion
    confirmacion.save()
    
    con = get_object_or_404(Confirmacion,pk = confirmacion.pk)
    return HttpResponse('ok')
    
def pdf(request):
    with open(settings.BASE_DIR+'/propuesta/static/contrato.pdf', 'rb') as pdf:
        response = HttpResponse(pdf.read(),content_type='application/pdf')
        response['Content-Disposition'] = 'filename=contrato.pdf'
        return response
    pdf.closed

administrador/templates/administrador/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es" class="">
    <head>
        <meta charset="utf-8" />
        <title>Sival: Administrador Propuestas</title>
        <meta name="description" content="app, web app, responsive, responsive layout, admin, admin panel, admin dashboard, flat, flat ui, ui kit, AngularJS, ui route, charts, widgets, components" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />



        <link href="{% static 'administrador/libs/assets/animate.css/animate.css' %}" rel="stylesheet">
        <link href="{% static 'administrador/libs/assets/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'administrador/libs/assets/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">
        <link href="{% static 'administrador/libs/jquery/bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet">


        <link href="{% static 'administrador/css/font.css' %}" rel="stylesheet">
        <link href="{% static 'administrador/css/app.css' %}" rel="stylesheet">
        <link href="{% static 'administrador/css/tabla.css' %}" rel="stylesheet">  
        <link href="{% static 'administrador/libs/jquery/plugins/integration/bootstrap/3/dataTables.bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'administrador/css/personal.css' %}" rel="stylesheet">
        <link href="{% static 'sweetalert/dist/sweetalert.css' %}" rel="stylesheet">
        {% block link %}{% endblock %}




    </head>
    <body>
        <div class="app app-header-fixed ">


            <!-- header -->
            <header id="header" class="app-header navbar" role="menu">
                <!-- navbar header -->
                <div class="navbar-header bg-dark">
                    <!-- brand -->
                    <a href="#/" class="navbar-brand text-lt logo">
                        <span class="hidden-folded m-l-xs ">Sival</span>
                    </a>
                    <!-- / brand -->
                </div>
                <!-- / navbar header -->

                <!-- navbar collapse -->
                <div class="collapse pos-rlt navbar-collapse box-shadow bg-white-only">
                    <!-- buttons -->

                    <div class=" navbar-nav titulo">
                        <h1>{% block title %}{% endblock %}</h1>
                    </div>
                </div>
                <!-- / navbar collapse -->
            </header>
            <!-- / header -->


            <!-- aside -->
            <aside id="aside" class="app-aside hidden-xs bg-dark aside-personal">
                <div class="aside-wrap">
                    <div class="navi-wrap">
                        <!-- user -->

                        <!-- nav -->
                        <nav ui-nav class="navi clearfix">
                            <ul class="nav">
                                <li>
                                    <a href="{% url 'administrador:administrador' %}" class="auto">
                                        <i class="fa fa-home"></i>
                                        <span class="font-bold">Panel principal</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'administrador:solicitud' %}">
                                        <i class="icon-list"></i>
                                        <span class="font-bold">Solicitudes</span>
                                    </a>
                                </li>    
                                <li>
                                    <a href="{% url 'administrador:propuestas' %}">
                                        <i class="glyphicon glyphicon-file"></i>
                                        <span class="font-bold">Propuestas</span>
                                    </a>
                                </li>    
                            </ul>
                        </nav>
                        <!-- nav -->

                        <!-- aside footer -->

                        <!-- / aside footer -->
                    </div>
                </div>
            </aside>
            <!-- / aside -->


            <!-- content -->
            <div id="content" class="app-content" role="main">
                <div class="app-content-body ">

                    <div class="wrapper-md contenido">
                        {% block body %}{% endblock %}
                    </div>
                </div>
            </div>
            <!-- /content -->

            <!-- footer -->
            <footer id="footer" class="app-footer" role="footer">
                <div class="wrapper b-t bg-light">
                    <span class="pull-right">2.1.0 <a href ui-scroll="app" class="m-l-sm text-muted"><i class="fa fa-long-arrow-up"></i></a></span>
                    &copy; 2015 Copyright.
                </div>
            </footer>
            <!-- / footer -->



        </div>


        <script type="text/javascript" src="{% static 'administrador/libs/jquery/jquery/dist/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'administrador/libs/jquery/datatables/media/js/jquery.dataTables.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'administrador/libs/jquery/plugins/integration/bootstrap/3/dataTables.bootstrap.js' %}"></script>
        <script type="text/javascript" src="{% static 'administrador/libs/jquery/bootstrap/dist/js/bootstrap.js' %}"></script>
        <script type="text/javascript" src="{% static 'administrador/js/ui-load.js' %}"></script>
        <script type="text/javascript" src="{% static 'administrador/js/ui-jp.config.js' %}"></script>
        <script type="text/javascript" src="{% static 'administrador/js/ui-jp.js' %}"></script>
        <script type="text/javascript" src="{% static 'administrador/js/ui-nav.js' %}"></script>
        <script type="text/javascript" src="{% static 'administrador/js/ui-toggle.js' %}"></script>
        <script type="text/javascript" src="{% static 'administrador/js/ui-client.js' %}"></script>
        <script type="text/javascript" src="{% static 'sweetalert/dist/sweetalert.min.js' %}"></script>
        {% block script %}{% endblock %}
        
        
        
    </body>
</html>

administrador/templates/administrador/principal.html
{% extends "administrador/index.html" %}
{% load staticfiles %}


{% block link %}
<link href="{% static 'administrador/css/load.css' %}" rel="stylesheet">
{% endblock %}


{% block title %}
Panel principal
{% endblock %}

{% block body %}
<div class="panel panel-default">
    <div class="panel-heading titulo">
        <h2>Solicitudes pendientes</h2>
    </div>
    <div class="table-responsive">

        <table  id='tabla-datos'class="table table-striped b-t b-b" > 
            <thead>
                <tr>
                <th  style="width:5%">Id</th>
                <th  style="width:10%">Nombre</th>
                <th  style="width:15%">Fecha de solicitud</th>
                <th  style="width:15%">Punto de salida</th>
                <th  style="width:15%">Punto de llegada</th>
                <th  style="width:10%">Ida y vuelta</th>
                <th  style="width:15%">Kms recorridos</th>
                <th  style="width:15%"></th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<div class="panel panel-default" style="display: none" id="contenedor2">
    <div class="panel-heading titulo">
        <h3>Enviar cotización</h3>
    </div>
    <div class="table-responsive interior">
        <div class="mi-contenedor">
            <div class="row mi-row">
                <div class="col-sm-4 " id="derehca">
                    <div class="panel panel-default formulario">
                        <div class="panel-heading font-bold">Formulario de cotización</div>
                        <div class="panel-body">
                            <form role="form" id="form-origen">
                                <div class="form-group">
                                    <label>Precio trayecto ida</label>                                    
                                    <div class="input-group m-b">
                                        <span class="input-group-addon">$</span>
                                        <input type="number" class="form-control" id="cmp1">
                                        <span class="input-group-addon">.00</span>
                                    </div>
                                </div>
                                <div class="form-group" id="campovuelta">
                                    <label>Precio trayecto vuelta</label>                                    
                                    <div class="input-group m-b">
                                        <span class="input-group-addon">$</span>
                                        <input type="number" class="form-control" id="cmp2" >
                                        <span class="input-group-addon">.00</span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Comentarios</label>
                                    <textarea rows="4" cols="50" id="comentarios" class="form-control" style="resize: none;"></textarea>
                                </div>

                                <button class="btn m-b-xs w-xs btn-dark form-control" style="width: 100%" id="pp1" type="button">Previsualizar cotización</button>
                                <button class="btn m-b-xs w-xs btn-success" type="submit" style="width: 100%">Enviar</button>                                                        
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8" id="izquierda">
                    <span class="col-sm-12" id="resumen">Resumen de solicitud</span>
                    <div class="col-sm-6">
                        <table  id='tabla-trayecto'class="table table-striped panel panel-default" > 
                            <thead>
                                <tr>
                                <th  style="width:50%" class="superior" id="s1">Trayecto de ida</th>
                                <th  style="width:50%" id="s2"><span id="text">Trayecto de vuelta</span> </th>                                                            
                                </tr>
                            </thead>
                            <tbody>
                                <tr role="row" class="odd">
                                <th>Fecha de salida</th>
                                <td><span id="fecha">20-10-2015</span></td>                                                               
                                </tr>
                                <tr role="row" class="odd">
                                <th>hora de salida</th>
                                <td><span id="hora">2:30pm</span></td>                                                               
                                </tr>
                                <tr role="row" class="odd">
                                <th>Km recorridos</th>
                                <td><span id="klm">2:30pm</span></td>                                                               
                                </tr>
                            </tbody>
                        </table>  
                        <button class="btn m-b-xs w-xs btn-primary" type="submit" style="width: 100%;margin-top: -10px;" id="but">Ve r mapa</button>
                    </div>
                    <div class="col-sm-6">
                        <table  id='tabla-info'class="table table-striped panel panel-default" > 
                            <thead>
                                <tr>
                                <th style="width:50%">Nombre</th>
                                <td style="width:50%;padding-left: 15px;" id="nom-tab">Carlos roso</td>
                                </tr>
                            </thead>

                            <tbody>

                                <tr role="row" class="odd">
                                <th>Email</th>
                                <td id="em-tab">Carlos roso</td>
                                </tr>                                                        
                                <tr role="row" class="odd">
                                <th>Fecha de solicitud</th>
                                <td id="fes-tab">20-10-2015</td>
                                </tr>
                                <tr role="row" class="odd">
                                <th>Ida y vuelta</th>
                                <td id="ida-tab">si</td>
                                </tr>
                                <tr role="row" class="odd">
                                <th>Numero de puestos</th>
                                <td id="ida-puestos">-1</td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="panel panel-default comentarios">
                            <span>Comentarios:</span>
                            <br>
                            <label id="comen">Hola esto es un comek as sdf sad fsa fas df asd fsa df sad fasd f asd fasd fas df asd fa f asd f</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="fondo-load" id="load-block">
    <div class="sk-fading-circle">
        <div class="sk-circle1 sk-circle"></div>
        <div class="sk-circle2 sk-circle"></div>
        <div class="sk-circle3 sk-circle"></div>
        <div class="sk-circle4 sk-circle"></div>
        <div class="sk-circle5 sk-circle"></div>
        <div class="sk-circle6 sk-circle"></div>
        <div class="sk-circle7 sk-circle"></div>
        <div class="sk-circle8 sk-circle"></div>
        <div class="sk-circle9 sk-circle"></div>
        <div class="sk-circle10 sk-circle"></div>
        <div class="sk-circle11 sk-circle"></div>
        <div class="sk-circle12 sk-circle"></div>
    </div>
</div>


{% endblock %}


{% block script %}
<script type="text/javascript" src="{% static 'administrador/js/propio.js' %}"></script>
{% endblock %}

administrador/templates/administrador/propuesta.html
{% extends "administrador/index.html" %}
{% load staticfiles %}

{% block link %}
{% endblock %}

{% block title %}
Propuestas
{% endblock %}

{% block body %}
<div class="panel panel-default">
    <div class="panel-heading titulo">
        <h2>Solicitudes</h2>
    </div>
    <div class="table-responsive">

        <table  id='tabla-propuestas'class="table table-striped b-t b-b" style="border: none"> 
            <thead>
                <tr>
                    <th  style="width:20%">Fecha propuesta</th>
                    <th  style="width:20%">Numero pasajeros</th>
                    <th  style="width:20%">Identificación</th>
                    <th  style="width:20%">Telefono</th>  
                    <th  style="width:20%">Tipo bus</th>                                            
                </tr>
            </thead>
        </table>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'administrador/js/propio.js' %}"></script>
<script type="text/javascript" src="{% static 'administrador/js/propuestas.js' %}"></script>
{% endblock %}

administrador/templates/administrador/solicitudes.html
{% extends "administrador/index.html" %}
{% load staticfiles %}

{% block link %}
{% endblock %}

{% block title %}
Solicitudes
{% endblock %}

{% block body %}
<div class="panel panel-default">
    <div class="panel-heading titulo">
        <h2>Solicitudes</h2>
    </div>
    <div class="table-responsive">

        <table  id='tabla-solicitud'class="table table-striped b-t b-b" > 
            <thead>
                <tr>
                    <th  style="width:5%">Id</th>
                    <th  style="width:10%">Fecha solicitud</th>
                    <th  style="width:15%">Punto de salida</th>
                    <th  style="width:15%">Punto de llegada</th>
                    <th  style="width:10%">Precio ida</th>  
                    <th  style="width:10%">Precio regreso</th>  
                    <th  style="width:10%">Respondida</th>  
                    <th  style="width:10%">Vista</th>  
                    <th  style="width:15%"></th>
                </tr>
            </thead>
        </table>
    </div>
</div>



<div class="panel panel-default" style="display: none" id="contenedor2">
    <div class="panel-heading titulo">
        <h3>Resumen de solicitud</h3>
    </div>
    <div class="table-responsive interior">
        <div class="mi-contenedor">
            <div class="row mi-row">
                <div class="col-sm-12" >
                    <span class="col-sm-12" id="resumen"></span>
                    <div class="col-sm-4">
                        <div class="panel panel-default comentarios">
                            <span>Comentarios propuesta:</span>
                            <br>
                            <label id="kk">Hola esto es un comek as sdf sad fsa fas df asd fsa df sad fasd f asd fasd fas df asd fa f asd f</label>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <table  id='tabla-trayecto'class="table table-striped panel panel-default" > 
                            <thead>
                                <tr>
                                    <th  style="width:50%" class="superior" id="s1">Trayecto de ida</th>
                                    <th  style="width:50%" id="s2"><span id="text">Trayecto de vuelta</span> </th>                                                            
                                </tr>
                            </thead>
                            <tbody>
                                <tr role="row" class="odd">
                                    <th>Fecha de salida</th>
                                    <td><span id="fecha">20-10-2015</span></td>                                                               
                                </tr>
                                <tr role="row" class="odd">
                                    <th>hora de salida</th>
                                    <td><span id="hora">2:30pm</span></td>                                                               
                                </tr>
                                <tr role="row" class="odd">
                                    <th>Km recorridos</th>
                                    <td><span id="klm">2:30pm</span></td>                                                               
                                </tr>
                            </tbody>
                        </table>  
                        <button class="btn m-b-xs w-xs btn-primary" type="submit" style="width: 100%;margin-top: -10px;" id="but">Ve r mapa</button>
                    </div>
                    <div class="col-sm-4">
                        <table  id='tabla-info'class="table table-striped panel panel-default" > 
                            <thead>
                                <tr>
                                    <th style="width:50%">Nombre</th>
                                    <td style="width:50%;padding-left: 15px;" id="nom-tab">Carlos roso</td>
                                </tr>
                            </thead>

                            <tbody>

                                <tr role="row" class="odd">
                                    <th>Email</th>
                                    <td id="em-tab">Carlos roso</td>
                                </tr>                                                        
                                <tr role="row" class="odd">
                                    <th>Fecha de solicitud</th>
                                    <td id="fes-tab">20-10-2015</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <th>Ida y vuelta</th>
                                    <td id="ida-tab">si</td>
                                </tr>
                                <tr role="row" class="odd">
                                    <th>Numero de puestos</th>
                                    <td id="ida-puestos">-1</td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="panel panel-default comentarios">
                            <span>Comentarios:</span>
                            <br>
                            <label id="comen">Hola esto es un comek as sdf sad fsa fas df asd fsa df sad fasd f asd fasd fas df asd fa f asd f</label>
                        </div>
                    </div>
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'administrador/js/propio.js' %}"></script>
<script type="text/javascript" src="{% static 'administrador/js/solicitud.js' %}"></script>
<script type="text/javascript" src="{% static 'administrador/js/jquery.number.min.js' %}"></script>
{% endblock %}