Cotizador/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('formulario.urls', namespace="formulario")),
    url(r'administrador/', include('administrador.urls', namespace="administrador")),
    url(r'propuesta/', include('propuesta.urls', namespace="propuesta")),
    url(r'^admin/', include(admin.site.urls)),
]

formulario/urls.py
'''
Created on 26/11/2015

@author: jose
'''

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^crear/$', views.crearRuta, name='crearRuta'),
    url(r'^mapa/$', views.verMapa, name='verMapa'),
    url(r'^mapa/informcacion/(?P<id>[0-9]+)/(?P<caminon>[0-9]+)$', views.verMapa2, name='verMapa2'),
    url(r'^tabla/$', views.verTabla, name='verTabla'),
]

formulario/models.py
from django.db import models


# Create your models here.

class Cotizacion(models.Model):
    nombre = models.CharField(max_length=200)
    correo = models.EmailField(max_length=254)
    comentarios = models.CharField(max_length=400)
    salida = models.DateTimeField()
    regreso = models.DateTimeField(null=True)
    fecha = models.DateTimeField(auto_now_add=True)
    camino = models.IntegerField()
    distancia = models.DecimalField(max_digits=100, decimal_places=5)
    distancia2 = models.DecimalField(max_digits=100, decimal_places=5, null=True)
    respondido = models.BooleanField(default=False)
    conductor = models.BooleanField(default=False)
    puestos = models.IntegerField()
    def __unicode__(self):  # __unicode__ on Python 2
        return (self.nombre + " / %s")%(str(self.fecha))
    
class Punto(models.Model):
    nombre = models.CharField(max_length=200)
    lat = models.DecimalField(max_digits=10, decimal_places=7)
    lng = models.DecimalField(max_digits=10, decimal_places=7)
    secuencia = models.IntegerField()
    CHOICES = (
                ('OR', 'origen'),
                ('DS', 'destino'),
    )
    camino = models.CharField(max_length=2, choices=CHOICES)
    cotizacion= models.ForeignKey(Cotizacion,on_delete=models.CASCADE)
    def __unicode__(self):              # __unicode__ on Python 2
        return self.nombre  

formulario/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
from .models import *
import json
import datetime

# Create your views here.

def index(request):
    context = {"post":"si"}
    return render(request, 'index.html', context)

def crearRuta(request):
    infomacion = request.POST['info']
    dicconario = json.loads(infomacion)
    cot = Cotizacion()
    cot.nombre = dicconario.get('nombre')
    cot.correo = dicconario.get('correo')
    cot.puestos = dicconario.get('puestos')
    cot.comentarios = dicconario.get('comentarios')
    cot.camino = dicconario.get('ruta')
    date = datetime.datetime.strptime(dicconario.get('salida'), "%m/%d/%Y %I:%M %p").strftime('%Y-%m-%d %H:%M')
    cot.salida = date
    cot.conductor = dicconario.get('conductor')
    cot.distancia = dicconario.get('distancia')
    cot.distancia2 = dicconario.get('distancia2')
    if dicconario.get('regreso')!= "":
        cot.regreso = datetime.datetime.strptime(dicconario.get('regreso'), "%m/%d/%Y %I:%M %p").strftime('%Y-%m-%d %H:%M')
    cot.save()
    ruta1 = json.loads(dicconario.get('rutaIda'))
    for i, value in enumerate(ruta1):
        punto = Punto()
        punto.secuencia = i
        punto.camino = 'OR'
        punto.lat = value.get('posicion').get('lat')
        punto.lng = value.get('posicion').get('lng')
        punto.cotizacion = cot
        punto.nombre = value.get('nombre')
        punto.save()
    
    ruta2 = json.loads(dicconario.get('rutaVenida'))
    for i, value in enumerate(ruta2):
        punto = Punto()
        punto.secuencia = i
        punto.camino = 'DS'
        punto.lat = value.get('posicion').get('lat')
        punto.lng = value.get('posicion').get('lng')
        punto.cotizacion = cot
        punto.nombre = value.get('nombre')
        punto.save()
    return HttpResponse("ruta guardada")

def verMapa(request):
    return render(request,'formulario/mapa.html')

def verMapa2(request,id,caminon):
    cotizacion = Cotizacion.objects.get(pk=id);
    if caminon=='1':
        puntos = Punto.objects.filter(cotizacion = cotizacion).filter(camino='OR').order_by('secuencia').values();
    else:
        puntos = Punto.objects.filter(cotizacion = cotizacion).filter(camino='DS').order_by('secuencia').values();
    
    serial = json.dumps(list(puntos), cls=DjangoJSONEncoder)
    context = {'ruta1' : serial}
    return render(request,'formulario/mapaVer.html',context)

def verTabla(request):
    return render(request,'formulario/tabla.html')

formulario/templates/formulario/mapa.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <style type="text/css">
            html, body {
                height: 100%;
                width: 100%;
                margin: 0;
                padding: 0;
            }

            #map {
                height: 100%;
                width: 100%;
            }
        </style>
        
        <link href="{% static 'formulario/css/bootstrap.min.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'date-picker/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}" />
        <link href="{% static 'formulario/css/style.css' %}" rel="stylesheet">
        <link href="{% static 'formulario/css/tabla.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link href="{% static 'sweetalert/dist/sweetalert.css' %}" rel="stylesheet">
        <link href="{% static 'formulario/css/switch.css' %}" rel="stylesheet">
        <link href="{% static 'formulario/css/switch2.css' %}" rel="stylesheet">
        <link href="{% static 'formulario/css/modal.css' %}" rel="stylesheet">
        <link href="{% static 'formulario/css/jquerytour.css' %}" rel="stylesheet">
        
        

        <script type="text/javascript" src="{% static 'formulario/js/jquery-2.1.4.min.js' %}"></script>        
        <script type="text/javascript" src="{% static 'formulario/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'sweetalert/dist/sweetalert.min.js' %}"></script>

    

    </head>
    <body>
        <div id="map" style="height: 100%"></div>
        <div class="container contenedor-global">
            <div class="row">
                <div class="col-sm-4 col-sm-offset-8 text-center">
                    <div class="container formulario-container">
                        <div class="row">
                            <div class="col-sm-10 col-sm-offset-1 text-center">
                                <form action="{% url 'formulario:crearRuta' %}" method="post" id="form-origen">
                                    {% csrf_token %} 
                                    
                                        <div class="inner-addon left-addon">
                                            <input type="text" name="origen" id='origen' placeholder="Punto de origen" class="botones-fomulario tour_1" >
                                            <i class="glyphicon glyphicon-map-marker mis-iconos"></i> 
                                            <i class="fa fa-exclamation iconos-validation" id="ic-origen"></i>
                                        </div>
                                    
                                    

                                    <div class="panel with-nav-tabs panel-primary">
                                        <div class="panel-heading">
                                            <ul class="nav nav-tabs">
                                                <li class="active"><a href="#tab1primary" data-toggle="tab" id="ida">Ida</a></li>
                                                <li><a href="#tab2primary" data-toggle="tab" id="regreso" class="tour_5">Regreso</a></li>
                                            </ul>
                                        </div>
                                        <div class="panel-body">
                                            <div class="tab-content">
                                                <div class="tab-pane fade in active" id="tab1primary">
                                                    <div id="intenalponint">
                                                        <div id = "puntos-div">                                                        
                                                        </div>                                                            
                                                    </div>
                                                    <hr>
                                                    <div class="cont-a">
                                                        <div class="inner-addon left-addon" id="cont1">
                                                            <input type="text" name="fecha" id="fecha1" placeholder="Fecha de salida" class="botones-fomulario tour_3" style="margin-bottom: 0px" />
                                                            <i class="glyphicon glyphicon-calendar mis-iconos" id = "icono-fecha"></i> 
                                                            <i class="fa fa-exclamation iconos-validation" id="ic-fecha"></i>
                                                            <script type="text/javascript">
                                                                $(function () {
                                                                $('#fecha1').datetimepicker();
                                                                });
                                                            </script>
                                                        </div>
                                                        <a href="#" id = "definir-ruta" class="tour_4">Agregar puntos</a> 
                                                    </div>
                                                </div>
                                                <div class="tab-pane fade" id="tab2primary">
                                                    <div id = "puntos-div-regreso"></div>
                                                    <hr>
                                                    <div class="inner-addon left-addon" id="cont2">
                                                        <input type="text" name="fecha" id="fecha2" placeholder="Fecha de salida" class="botones-fomulario" style="margin-bottom: 0px"/>
                                                        <i class="glyphicon glyphicon-calendar mis-iconos" id = "icono-fecha"></i> 
                                                        <script type="text/javascript">
                                                            $(function () {
                                                            $('#fecha2').datetimepicker();
                                                            });
                                                        </script>
                                                    </div>
                                                    <div class="cont-a">
                                                        <a href="#" id = "definir-ruta-regreso">Agregar puntos</a> 
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="inner-addon left-addon">
                                        <input type="text" name="destino" id="destino"
                                               placeholder="Punto de destino" class="botones-fomulario tour_2"
                                               > 
                                        <i class="glyphicon glyphicon-map-marker mis-iconos"></i> 
                                        <i class="fa fa-exclamation iconos-validation" id="ic-destino"></i>
                                    </div>
                                    <div class="inner-addon left-addon">
                                        <input type="text" name="nombre" id="nombre" placeholder="Nombre" class="botones-fomulario" > 
                                        <i class="glyphicon glyphicon-user mis-iconos"></i>
                                        <i class="fa fa-exclamation iconos-validation" id="ic-nombre"></i>
                                    </div>
                                    <div class="inner-addon left-addon">
                                        <input type="email" name="email" id="email" placeholder="Email" class="botones-fomulario" >
                                        <i class="glyphicon glyphicon-envelope mis-iconos"></i>
                                        <i class="fa fa-exclamation iconos-validation" id="ic-email"></i>
                                    </div>
                                    <div class="inner-addon left-addon">
                                        <input type="number" name="puestos" id="puestos" placeholder="Puestos" class="botones-fomulario" min="1">
                                        <i class="glyphicon fa fa-ticket mis-iconos"></i>
                                        <i class="fa fa-exclamation iconos-validation" id="ic-puesto"></i>
                                    </div>
                                    
                                    
                                    <div class="container-s" id="swt1">
                                        <div class="switch white tour_6">
                                            <input type="radio" name="switch" id="switch-off" value="1" checked>
                                            <input type="radio" name="switch" id="switch-on" value="2" >
                                            <label for="switch-off">Solo ida</label>
                                            <label for="switch-on">Ida regreso</label>
                                            <span class="toggle"></span>
                                        </div> 
                                    </div>                                     

                                    <input type="checkbox" id="c1" name="cc" />
                                    <label for="c1" class="tour_8"><span></span>Alquilar conductor</label>
                                    
                                    <textarea rows="4" cols="50" placeholder="Comentarios " id="comentarios" class="botones-fomulario" resize = "false"></textarea>
                                    <input type="submit" value="Enviar" class="btn-enviar tour_7" />
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script type="text/javascript" src="{% static 'date-picker/moment/min/moment.min.js' %} "></script>
        <script type="text/javascript" src="{% static 'date-picker/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %} "></script>
        <script type="text/javascript" src="{% static 'formulario/js/mapa.js' %}"></script>
        <script type="text/javascript" src="{% static 'formulario/js/tour.js' %}"></script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcEPNy2nmaDLDzM9u4q3XWokUK7UVAUcA&callback=initMap&libraries=places">
        </script>             
        
        
    </body>
</html>

formulario/templates/formulario/mapaVer.html
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
{% load staticfiles %}
<html>
    <head>
        <title>Sival mapa</title>
        <meta charset="UTF-8">
        <style type="text/css">
            html, body {
                height: 100%;
                width: 100%;
                margin: 0;
                padding: 0;
            }

            #map {
                height: 100%;
                width: 100%;
            }
        </style>
    </head>
    <body>
        <div id="map" style="height: 100%"></div>  
        <script type="text/javascript"> 
            var ida = "{{ruta1}}";
        </script>
        <script type="text/javascript" src="{% static 'formulario/js/mapa2.js' %}"></script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcEPNy2nmaDLDzM9u4q3XWokUK7UVAUcA&callback=initMap&libraries=places">
        </script>
    </body>
</html>

formulario/templates/formulario/tabla.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <style type="text/css">
            html, body {
                height: 100%;
                width: 100%;
                margin: 0;
                padding: 0;
            }

            #map {
                height: 100%;
                width: 100%;
            }
        </style>
        <meta charset="UTF-8">
        <title>Insert title here</title>
        <link href="{% static 'formulario/css/bootstrap.min.css' %}"
              rel="stylesheet">
        <link href="{% static 'formulario/css/style.css' %}" rel="stylesheet">




        <script type="text/javascript" src="{% static 'formulario/js/jquery-2.1.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'formulario/js/bootstrap.min.js' %}"></script>


        <link type="text/css" rel="stylesheet" href="{% static 'tab/pwstabs/assets/jquery.pwstabs.css' %}">
        <script type="text/javascript" src="{% static 'tab/pwstabs/assets/jquery.pwstabs.js' %}"></script>

        <link href="{% static 'formulario/css/tabla.css' %}" rel="stylesheet">

    </head>
    <body>

        <div id="map" style="height: 100%"></div>
        <div class="container contenedor-global">
            <div class="row">
                <div class="col-sm-3 col-sm-offset-9 text-center">

                    <div class="tabla">
                        <div data-pws-tab="ida" data-pws-tab-name="Ruta de ida">
                            ida
                        </div>
                        <div data-pws-tab="vuelta" data-pws-tab-name="ruta de regreso">EL NUEVO CAMBIO
                        </div>
                    </div>

                </div>
            </div>
        </div>







        <script type="text/javascript" src="{% static 'date-picker/moment/min/moment.min.js' %} "></script>
        <script type="text/javascript" src="{% static 'date-picker/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %} "></script>
        <script type="text/javascript" src="{% static 'formulario/js/mapa.js' %}"></script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcEPNy2nmaDLDzM9u4q3XWokUK7UVAUcA&callback=initMap&libraries=places">
        </script>
    </body>
</html>